name: Shailyay Interrogation
on:
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Create interrogation file
        run: |
          mkdir -p shaily
          cat <<EOF > shaily/interrogation-${{ env.date }}.md
## Shailyay interrogation

Create \`interrogation_${{ env.date }}.md\` on a branch linked to this PR and answer the following:

1. What do you think I like about you?  
2. What do you like about me?
EOF

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add interrogation for ${{ env.date }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          base: main
          branch: interrogation-${{ env.date }}
          title: "Shailyay interrogation ${{ env.date }} ğŸ’Œ"
          body: |
            ğŸ•µï¸ Your task:
            - [ ] Go to **Files changed**
            - [ ] Answer the two prompts
            - [ ] Submit the PR when youâ€™re done!

            ğŸ‘‰ **Will you go to the ball with me, Shaily?**
          labels: ğŸ’Œ, question
